# Generated by Django 3.0.5 on 2020-05-13 17:50

from django.db import migrations, models
import pdvm_base.pdvm_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdvm_posts',
            fields=[
                ('userId', models.CharField(max_length=10)),
                ('id', models.UUIDField(default=pdvm_base.pdvm_util.getNewId, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
