# Generated by Django 3.0.5 on 2020-05-14 17:15

from django.db import migrations, models
import pdvm_base.pdvm_util


class Migration(migrations.Migration):

    dependencies = [
        ('pdvm_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdvm_comments',
            fields=[
                ('postId', models.CharField(max_length=10)),
                ('id', models.UUIDField(default=pdvm_base.pdvm_util.getNewId, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
    ]
