# Generated by Django 3.0.5 on 2020-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvm_posts', '0002_pdvm_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdvm_comments',
            name='postId',
            field=models.UUIDField(),
        ),
    ]
